stages:
  - maventry
  - androidtry

maven-build:   #this is a JOB
  stage: maventry
  tags:
    - chandra_backend  					# this is LINK to the shell runner on the remote-server 
  script:
    - cd Backend/Demo2					#change directory to where you have your springboot application
    - mvn package

android-build:
  image: gjandres/android-ci:latest
  stage: androidbuild
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/gradlew
  tags:
   - Frontend-Runner
  script:
    - cd Frontend
    - ./gradlew build
  artifacts:
    paths:
    - Android_test/app/build/outputs/

android-test:
  image: gjandres/android-ci:latest
  stage: androidtest
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/gradlew
  tags:
   - Frontend-Runner
  script:
    - cd Frontend
    - ./gradlew test

